version: '3.8'

services:
  pool-maintainer-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5080:5080"
      - "6080:6080"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
    environment:
      - NODE_ENV=development
      - VITE_PORT=5080
      - STORYBOOK_PORT=6080
    command: bun run dev --host 0.0.0.0